# SPDX-License-Identifier: GPL-2.0

# Nova DRM driver - C implementation (ported from Rust)
nova-y := \
	nova.o \
	driver.o \
	file.o \
	gem.o \
	nova_file.o \
	uapi.o

obj-$(CONFIG_DRM_NOVA) += nova.o
